# Generated by Django 3.2.3 on 2021-11-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_tools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mergedpdf',
            old_name='file',
            new_name='pdf_files',
        ),
    ]
