# Generated by Django 3.2.3 on 2021-11-18 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_tools', '0003_uploadpdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadPdf',
        ),
        migrations.RenameField(
            model_name='mergedpdf',
            old_name='pdf_files',
            new_name='pdf_file',
        ),
    ]
