# Generated by Django 3.2.3 on 2021-11-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_tools', '0004_auto_20211118_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mergedpdf',
            old_name='pdf_file',
            new_name='pdf_file1',
        ),
        migrations.AddField(
            model_name='mergedpdf',
            name='pdf_file2',
            field=models.FileField(default='default.pdf', upload_to='merged_pdf/'),
        ),
        migrations.AddField(
            model_name='mergedpdf',
            name='pdf_file3',
            field=models.FileField(blank=True, default='default.pdf', null=True, upload_to='merged_pdf/'),
        ),
        migrations.AddField(
            model_name='mergedpdf',
            name='pdf_file4',
            field=models.FileField(blank=True, default='default.pdf', null=True, upload_to='merged_pdf/'),
        ),
        migrations.AddField(
            model_name='mergedpdf',
            name='pdf_file5',
            field=models.FileField(blank=True, default='default.pdf', null=True, upload_to='merged_pdf/'),
        ),
    ]
