# Generated by Django 3.2.3 on 2021-11-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_tools', '0005_auto_20211118_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergedpdf',
            name='pdf_file1',
            field=models.FileField(default='default.pdf', upload_to='pdf_files_for_merging/'),
        ),
        migrations.AlterField(
            model_name='mergedpdf',
            name='pdf_file2',
            field=models.FileField(default='default.pdf', upload_to='pdf_files_for_merging/'),
        ),
        migrations.AlterField(
            model_name='mergedpdf',
            name='pdf_file3',
            field=models.FileField(blank=True, default='default.pdf', null=True, upload_to='pdf_files_for_merging/'),
        ),
        migrations.AlterField(
            model_name='mergedpdf',
            name='pdf_file4',
            field=models.FileField(blank=True, default='default.pdf', null=True, upload_to='pdf_files_for_merging/'),
        ),
        migrations.AlterField(
            model_name='mergedpdf',
            name='pdf_file5',
            field=models.FileField(blank=True, default='default.pdf', null=True, upload_to='pdf_files_for_merging/'),
        ),
        migrations.AlterField(
            model_name='passwordedpdf',
            name='file',
            field=models.FileField(default='default.pdf', upload_to='pdf_files_for_passwording/'),
        ),
    ]
