# Generated by Django 3.2.3 on 2021-11-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_tools', '0007_mergedpdf_pdf_file6'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MergedPDF',
            new_name='PDFtoMerge',
        ),
        migrations.AlterModelOptions(
            name='pdftomerge',
            options={'verbose_name_plural': 'PDFtoMerge'},
        ),
    ]
