# Generated by Django 3.2.3 on 2021-11-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_tools', '0009_mergedpdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mergedpdf',
            old_name='merged_pdf_file',
            new_name='pdf_file',
        ),
    ]
