# Generated by Django 3.2.3 on 2021-11-19 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_tools', '0015_auto_20211119_0927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MergedPDF',
        ),
    ]
