# Generated by Django 3.2.3 on 2021-11-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_tools', '0016_delete_mergedpdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdftopassword',
            name='pdf_file',
            field=models.FileField(default='default.pdf', upload_to='pdf_files_for_passwording/'),
        ),
    ]
