"""
Django settings for ogunkuade_pdf_tools project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import environ
from django.contrib.messages import constants as messages
import django_heroku # new line (heroku)



# INITIALIZE ENVIRONMENT VARIABLES
env = environ.Env()

# READING .env FILE
environ.Env.read_env()




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


TEMPLATE_DIR_1 = BASE_DIR / 'pdf_tools/templates'           # TEMPLATES DIRECTORY FOR FIRST APP


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['ogunkuadepdftools.herokuapp.com', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pdf_tools',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',           # new line (heroku)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ogunkuade_pdf_tools.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ogunkuade_pdf_tools.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': env("DATABASE_NAME"),                   # database name
        'USER': env("DATABASE_USER"),                   # database user
        'PASSWORD': env("DATABASE_PASSWORD"),           # database password
        'HOST': '127.0.0.1',                            # database host
        'PORT': '5432',                                 # database port
    }
}




# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

# new line (heroku)
# --------------------------------------------------------
STATIC_URL = '/static/'                         

STATICFILES_DIRS = [BASE_DIR / 'static']       

STATIC_ROOT = BASE_DIR / 'static_root'   

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage' 




# DEFINING THE MEDIA URL
MEDIA_URL = '/media/'


# DEFINING THE MEDIA LOCATION
MEDIA_ROOT = BASE_DIR / 'media'




# merging pdf files
# -----------------------------------------------------

# media url for uploaded pdf files
PDF_MERGE_URL_SOURCE = BASE_DIR / 'media/pdf_files_for_merging/'

# media url for merged pdf files
# PDF_MERGE_FINAL = BASE_DIR / 'media/merged_pdf/Merged_File.pdf'
PDF_MERGE_FINAL = BASE_DIR / 'media/merged_pdf/'



# passwording pdf files
# -----------------------------------------------------

# media url for passworded pdf files
PDF_PASSWORD_URL_SOURCE = BASE_DIR / 'media/pdf_files_for_passwording/'

# media url for passworded pdf files
PDF_PASSWORD_FINAL = BASE_DIR / 'media/passworded_pdf/'




# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'





# new line (heroku)
# --------------------------------------------------------
import dj_database_url 
prod_db  =  dj_database_url.config(conn_max_age=500)
DATABASES['default'].update(prod_db)



# new line (heroku)
# --------------------------------------------------------
django_heroku.settings(locals())    # new line





